import { Tables } from "@/integrations/supabase/types";

type Position3D = {
  x: number;
  z: number;
  rotation: number;
};

export const mockStreets: Tables<"streets">[] = [
  {
    id: "food-street",
    slug: "food-street",
    name: "Food Street",
    category: "Restaurants & Cafes",
    description: "A cozy culinary lane packed with tasting pods and neon kitchen fronts.",
    is_active: true,
    created_at: new Date().toISOString(),
  },
];

const foodStreetPositions: { label: string; position: Position3D; sort: number }[] = [
  { label: "Spice Gate", position: { x: -6, z: 8, rotation: Math.PI / 2 }, sort: 1 },
  { label: "Grill House", position: { x: 2, z: 3, rotation: Math.PI / 2 }, sort: 2 },
  { label: "Dessert Hub", position: { x: 10, z: -2, rotation: 0 }, sort: 3 },
  { label: "Fresh Market", position: { x: 2, z: -9, rotation: -Math.PI / 2 }, sort: 4 },
  { label: "Tea Corner", position: { x: -8, z: -4, rotation: -Math.PI }, sort: 5 },
];

export const mockSpotsByStreetSlug: Record<string, Tables<"shop_spots">[]> = {
  "food-street": foodStreetPositions.map((spot) => ({
    id: `food-${spot.sort}`,
    street_id: "food-street",
    spot_label: spot.label,
    position_3d: spot.position,
    sort_order: spot.sort,
    created_at: new Date().toISOString(),
  })),
};

export const mockShopsByStreetSlug: Record<string, Tables<"shops">[]> = {
  "food-street": [
    {
      id: "food-shop-1",
      spot_id: "food-1",
      merchant_id: "mock",
      name: "Spice Gate Eats",
    category: "Street Food",
    status: "active",
    primary_color: "#FF7043",
    accent_color: "#FFD180",
    facade_template: "modern_neon",
    signage_font: "retro",
    logo_url: null,
    external_link: null,
    texture_template: null,
    texture_url: null,
    branch_label: "Main Pod",
    branch_justification: "Launch kiosk for tasting flights.",
    admin_notes: null,
    duplicate_brand: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
    {
      id: "food-shop-2",
      spot_id: "food-2",
      merchant_id: "mock",
      name: "Grill House Lab",
      category: "Grill",
      status: "active",
      primary_color: "#FF8A65",
      accent_color: "#4DB6AC",
      facade_template: "modern_neon",
      signage_font: "sleek",
      logo_url: null,
      external_link: null,
      texture_template: null,
      texture_url: null,
      admin_notes: null,
      duplicate_brand: false,
      branch_label: "Test Kitchen",
      branch_justification: "Prototype menu with tasting tickets.",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "food-shop-3",
      spot_id: "food-3",
      merchant_id: "mock",
      name: "Sweet Stack",
      category: "Desserts",
      status: "active",
      primary_color: "#F06292",
      accent_color: "#BA68C8",
      facade_template: "modern_neon",
      signage_font: "playful",
      logo_url: null,
      external_link: null,
      texture_template: null,
      texture_url: null,
      admin_notes: null,
      duplicate_brand: false,
      branch_label: "Dessert Pod",
      branch_justification: "New layered desserts showcase.",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "food-shop-4",
      spot_id: "food-4",
      merchant_id: "mock",
      name: "Farm Fresh",
      category: "Organic",
      status: "active",
      primary_color: "#81C784",
      accent_color: "#AED581",
      facade_template: "modern_neon",
      signage_font: "classic",
      logo_url: null,
      external_link: null,
      texture_template: null,
      texture_url: null,
      admin_notes: null,
      duplicate_brand: false,
      branch_label: "Harvest Lane",
      branch_justification: "Pop-up produce tastings.",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "food-shop-5",
      spot_id: "food-5",
      merchant_id: "mock",
      name: "Tea Corner",
      category: "Tea & Coffee",
      status: "active",
      primary_color: "#4DB6AC",
      accent_color: "#80CBC4",
      facade_template: "modern_neon",
      signage_font: "serene",
      logo_url: null,
      external_link: null,
      texture_template: null,
      texture_url: null,
      admin_notes: null,
      duplicate_brand: false,
      branch_label: "Tea Dock",
      branch_justification: "Quiet tasting nook for brews.",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
};
